#ci.gocd.yaml
format_version: 9
pipelines:
  loan-gateway-build:
    materials:
      cdc:
        git: https://github.com/SwapnilSankla/cdc.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              tasks:
                - exec:
                    command: sh
                    arguments: "gradle clean build"